version: '3.7'
services:
    postgres-db:
        container_name: activity-tracker-db
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        # ports:
        #   - 5432:5432
        expose:
          - 5432
        volumes: 
          # - ./postgres-data:/var/lib/postgresql/data
          - ./src/main/resources/GarminActivities.csv:/var/lib/postgresql/activity-data/GarminActivities.csv
          # copy the sql script to create tables and enter the seed data
          - ./sql/create_and_seed_tables.sql:/docker-entrypoint-initdb.d/create_and_seed_tables.sql
    backend:
      container_name: activity-tracker-backend
      # image: kburke96/activitytracker
      build: .
      ports:
        - 8080:8080
      depends_on:
        - postgres-db
    frontend:
      container_name: activity-tracker-frontend
      # image: kburke96/activitytracker-ui
      build: ./frontend
      ports: 
        - 3000:3000
      depends_on:
        - backend
      command: npm start
